services:
  - type: web
    name: wedify-backend
    env: python
    region: ohio
    plan: free
    buildCommand: ./backend/build.sh
    startCommand: cd backend && gunicorn wedify_project.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: wedify-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".render.com"
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false

databases:
  - name: wedify-db
    plan: free
    region: ohio
